# Generated by Django 5.0.6 on 2024-07-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todos",
            old_name="list",
            new_name="project",
        ),
    ]
