# Generated by Django 5.0.6 on 2024-07-05 08:01

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_alter_todos_add_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FF0000", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
