# Generated by Django 5.0.6 on 2024-07-05 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_project_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="color",
        ),
    ]
